// <auto-generated />
using System;
using MecatolArchives.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MecatolArchives.DataAccess.Migrations.Mssql.Migrations
{
    [DbContext(typeof(MecatolArchivesDbContext))]
    [Migration("20251210071007_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContentPlay", b =>
                {
                    b.Property<Guid>("ExpansionsIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaysIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExpansionsIdentifier", "PlaysIdentifier");

                    b.HasIndex("PlaysIdentifier");

                    b.ToTable("ContentPlay");
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Colour", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Identifier");

                    b.ToTable("Colours");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("cbdfdda9-13bf-4a45-be5d-0882f6dcbad8"),
                            Hex = "",
                            Name = "_Unknown_"
                        },
                        new
                        {
                            Identifier = new Guid("564f166e-33cb-45cc-bca6-1b2d16b8bf60"),
                            Hex = "#000000",
                            Name = "Black"
                        },
                        new
                        {
                            Identifier = new Guid("53bf36a1-669c-41ed-9ced-4fa94ba038ee"),
                            Hex = "#FF0000",
                            Name = "Red"
                        },
                        new
                        {
                            Identifier = new Guid("e8ca7b27-00cd-4a2a-bc7f-17105e690e2d"),
                            Hex = "#008000",
                            Name = "Green"
                        },
                        new
                        {
                            Identifier = new Guid("51b6cc96-0e35-48f9-8665-b50bbe3fdb44"),
                            Hex = "#FFFF00",
                            Name = "Yellow"
                        },
                        new
                        {
                            Identifier = new Guid("a9c3b568-d781-452d-91ae-44b0cc8e7020"),
                            Hex = "#800080",
                            Name = "Purple"
                        },
                        new
                        {
                            Identifier = new Guid("43c078a5-0561-40f0-8adc-92afa32eaeb0"),
                            Hex = "#FFA500",
                            Name = "Orange"
                        },
                        new
                        {
                            Identifier = new Guid("daceda53-e450-4fce-82d4-ef1cdd312e38"),
                            Hex = "#FF00FF",
                            Name = "Magenta"
                        },
                        new
                        {
                            Identifier = new Guid("08ddef19-bd82-4eda-b245-5e84e8da38d9"),
                            Hex = "#FFFFFF",
                            Name = "White"
                        },
                        new
                        {
                            Identifier = new Guid("b5616b41-2821-4a27-85dc-fa81b899e578"),
                            Hex = "#0000FF",
                            Name = "Blue"
                        });
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Content", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Identifier");

                    b.ToTable("Expansions");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("fb08d4e6-5ac1-4cbf-8eb9-166f6c5e41f0"),
                            Name = "Prophecy of Kings"
                        },
                        new
                        {
                            Identifier = new Guid("5615f96a-cce5-41a6-90d8-91aed8cd1645"),
                            Name = "Thunder's Edge"
                        },
                        new
                        {
                            Identifier = new Guid("21fbcaf7-ae17-4db7-851a-dc65eb3ba60f"),
                            Name = "Codex I: Ordinian"
                        },
                        new
                        {
                            Identifier = new Guid("9420502f-4ef0-4887-add4-3d8a4941016a"),
                            Name = "Codex II: Affinity"
                        },
                        new
                        {
                            Identifier = new Guid("1eb732ba-74ac-4993-943e-cd6f3650d310"),
                            Name = "Codex III: Vigil"
                        },
                        new
                        {
                            Identifier = new Guid("f77349c8-dc28-424a-b0bc-16057f15d18e"),
                            Name = "Codex IV: Liberation"
                        },
                        new
                        {
                            Identifier = new Guid("69996b68-7083-43db-ba63-efffb80df833"),
                            Name = "Absol's Agendas & Relics"
                        },
                        new
                        {
                            Identifier = new Guid("7606e091-1f8d-4e58-8d48-8c93dc65b9ad"),
                            Name = "Discordant Stars"
                        },
                        new
                        {
                            Identifier = new Guid("dfaeec44-34c8-4bad-94c2-0f69b9e27f87"),
                            Name = "Uncharted Space"
                        });
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Faction", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Identifier");

                    b.ToTable("Factions");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("51ee1c82-279b-444c-a6aa-a8cd475612fd"),
                            Active = true,
                            Name = "The Council Keleres",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Council_Keleres"
                        },
                        new
                        {
                            Identifier = new Guid("609382d1-c969-4144-916a-ad4c13df1352"),
                            Active = true,
                            Name = "_Unknown_"
                        },
                        new
                        {
                            Identifier = new Guid("11ee6931-58d5-4808-b2c5-e3d4b7bf4343"),
                            Active = true,
                            Name = "The Arborec",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Arborec"
                        },
                        new
                        {
                            Identifier = new Guid("e4d8ad5c-cf62-4001-9b81-f2a31bd87b0d"),
                            Active = true,
                            Name = "The Barony of Letnev",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Barony_of_Letnev"
                        },
                        new
                        {
                            Identifier = new Guid("b01aaa66-1888-4926-803e-95a864057219"),
                            Active = true,
                            Name = "The Clan of Saar",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Clan_of_Saar"
                        },
                        new
                        {
                            Identifier = new Guid("fcae96dd-793a-4393-9f5f-f378ff167b12"),
                            Active = true,
                            Name = "The Embers of Muaat",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Embers_of_Muaat"
                        },
                        new
                        {
                            Identifier = new Guid("c9a5311a-4798-44c5-8b97-3a5bc4eaa01a"),
                            Active = true,
                            Name = "The Emirates of Hacan",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Emirates_of_Hacan"
                        },
                        new
                        {
                            Identifier = new Guid("a386b3e8-683b-4e7e-9fba-3361bdbbeef1"),
                            Active = true,
                            Name = "The Federation of Sol",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Federation_of_Sol"
                        },
                        new
                        {
                            Identifier = new Guid("2e017142-848a-4203-a109-1fa905a5db04"),
                            Active = true,
                            Name = "The Ghosts of Creuss",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Ghosts_of_Creuss"
                        },
                        new
                        {
                            Identifier = new Guid("4df36a67-6b3d-4966-ae0c-6ebdb6d0a97d"),
                            Active = true,
                            Name = "The L1Z1X Mindnet",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_L1Z1X_Mindnet"
                        },
                        new
                        {
                            Identifier = new Guid("c765da52-404b-4073-8c0c-003537169b4c"),
                            Active = true,
                            Name = "The Mentak Coalition",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Mentak_Coalition"
                        },
                        new
                        {
                            Identifier = new Guid("2002e0b3-603f-4b66-8268-2ca8ab2bfce4"),
                            Active = true,
                            Name = "The Naalu Collective",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Naalu_Collective"
                        },
                        new
                        {
                            Identifier = new Guid("79c4217c-dc20-46fe-9e0b-44e852dfc64b"),
                            Active = true,
                            Name = "The Nekro Virus",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Nekro_Virus"
                        },
                        new
                        {
                            Identifier = new Guid("1a5777dc-4106-46ec-8168-596c7c9edd36"),
                            Active = true,
                            Name = "Sardakk N'orr",
                            Url = "https://twilight-imperium.fandom.com/wiki/Sardakk_N%27orr"
                        },
                        new
                        {
                            Identifier = new Guid("0cc14756-19f7-42ef-acd0-156fab6bcd2b"),
                            Active = true,
                            Name = "The Universities of Jol-Nar",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Universities_of_Jol-Nar"
                        },
                        new
                        {
                            Identifier = new Guid("9b8cf62c-9c94-49aa-b55b-11a8f4f9a7c9"),
                            Active = true,
                            Name = "The Winnu",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Winnu"
                        },
                        new
                        {
                            Identifier = new Guid("279eefc5-4bd3-41be-93d0-b49bd6e9b7d6"),
                            Active = true,
                            Name = "The Xxcha Kingdom",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Xxcha_Kingdom"
                        },
                        new
                        {
                            Identifier = new Guid("2c637584-cdbb-485e-8c3f-bc713eebaa03"),
                            Active = true,
                            Name = "The Yin Brotherhood",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Yin_Brotherhood"
                        },
                        new
                        {
                            Identifier = new Guid("5265b1f2-4422-4d0b-8711-582330d9afe4"),
                            Active = true,
                            Name = "The Yssaril Tribes",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Yssaril_Tribes"
                        },
                        new
                        {
                            Identifier = new Guid("be81d0fd-0ba8-4d55-ac65-4eb66d49028a"),
                            Active = true,
                            Name = "The Argent Flight",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Argent_Flight"
                        },
                        new
                        {
                            Identifier = new Guid("f39815c4-b651-4ed4-86e0-5b4f5f6128ef"),
                            Active = true,
                            Name = "The Empyrean",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Empyrean"
                        },
                        new
                        {
                            Identifier = new Guid("2fffa08d-40ab-4e29-8e4a-0cda97b664be"),
                            Active = true,
                            Name = "The Mahact Gene-Sorcerers",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Mahact_Gene-Sorcerers"
                        },
                        new
                        {
                            Identifier = new Guid("26251032-94c9-4331-8ccf-697755213fad"),
                            Active = true,
                            Name = "The Naaz-Rokha Alliance",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Naaz-Rokha_Alliance"
                        },
                        new
                        {
                            Identifier = new Guid("4210c2bb-f773-4721-907b-1c3e1cd11357"),
                            Active = true,
                            Name = "The Nomad",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Nomad"
                        },
                        new
                        {
                            Identifier = new Guid("c4e77f65-5a61-404f-8793-b672ccdb29a4"),
                            Active = true,
                            Name = "The Titans of UL",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Titans_of_Ul"
                        },
                        new
                        {
                            Identifier = new Guid("91da5e70-a3db-4168-b18d-61ae7b899b48"),
                            Active = true,
                            Name = "The Vuil'Raith Cabal",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Vuil%27Raith_Cabal"
                        },
                        new
                        {
                            Identifier = new Guid("fcbf11ee-afe1-44aa-abd0-497d0baa1ee8"),
                            Active = true,
                            Name = "The Crimson Rebellion",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Crimson_Rebellion"
                        },
                        new
                        {
                            Identifier = new Guid("981e095a-55e0-4f35-8105-614eaa9cda43"),
                            Active = true,
                            Name = "The Deepwrought Scholarate",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Deepwrought_Scholarate"
                        },
                        new
                        {
                            Identifier = new Guid("8d975e74-efc4-4297-a7c0-85c2bbe5d55d"),
                            Active = true,
                            Name = "The Firmament / The Obsidian",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Firmament_/_The_Obsidian"
                        },
                        new
                        {
                            Identifier = new Guid("91bd2e7f-80ab-4e2f-df30-5c6d7e8f9011"),
                            Active = true,
                            Name = "Last Bastion",
                            Url = "https://twilight-imperium.fandom.com/wiki/Last_Bastion"
                        },
                        new
                        {
                            Identifier = new Guid("a2ce3f80-91bc-4f30-ef41-6d7e8f901122"),
                            Active = true,
                            Name = "The Ral Nel Consortium",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Ral_Nel_Consortium"
                        },
                        new
                        {
                            Identifier = new Guid("b3df4091-a2cd-4031-f052-7e8f90112233"),
                            Active = true,
                            Name = "The Shipwrights of Axis",
                            Url = "https://twilight-imperium.fandom.com/wiki/Shipwrights_of_Axis_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("c4e050a2-b3de-4132-0063-8f9011223344"),
                            Active = true,
                            Name = "The Celdauri Trade Confederation",
                            Url = "https://twilight-imperium.fandom.com/wiki/Celdauri_Trade_Confederation_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("d5f161b3-c4e0-4233-1164-901122334455"),
                            Active = true,
                            Name = "The Savages of Cymiae",
                            Url = "https://twilight-imperium.fandom.com/wiki/Savages_of_Cymiae_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("e60272c4-d5f1-4334-2265-011223344556"),
                            Active = true,
                            Name = "The Dih-Mohn Flotilla",
                            Url = "https://twilight-imperium.fandom.com/wiki/Dih-Mohn_Flotilla_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("f71383d5-e602-4435-3366-122334455667"),
                            Active = true,
                            Name = "The Florzen Profiteers",
                            Url = "https://twilight-imperium.fandom.com/wiki/Florzen_Profiteers_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("081a94e6-f713-4536-4467-233445566778"),
                            Active = true,
                            Name = "The Free Systems of Compacts",
                            Url = "https://twilight-imperium.fandom.com/wiki/Free_Systems_Compact_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("192ba5f7-081a-4637-5568-344556667889"),
                            Active = true,
                            Name = "The Ghemina Raiders",
                            Url = "https://twilight-imperium.fandom.com/wiki/Ghemina_Raiders_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("2a3cb608-192b-4738-6669-45566778899a"),
                            Active = true,
                            Name = "The Augurs of Ilyxum",
                            Url = "https://twilight-imperium.fandom.com/wiki/Augurs_of_Ilyxum_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("3b4dc719-2a3c-4839-777a-566778899a0b"),
                            Active = true,
                            Name = "The Kollecc Society",
                            Url = "https://twilight-imperium.fandom.com/wiki/Kollecc_Society_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("4c5ed82a-3b4d-493a-888b-6778899a0b1c"),
                            Active = true,
                            Name = "The Kortali Tribunal",
                            Url = "https://twilight-imperium.fandom.com/wiki/Kortali_Tribunal_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("5d6fe93b-4c5e-4a3b-999c-78899a0b1c2d"),
                            Active = true,
                            Name = "The Li-Zho Dynasty",
                            Url = "https://twilight-imperium.fandom.com/wiki/Li-Zho_Dynasty_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("6e70fa4c-5d6f-4b4c-a0ad-899a0b1c2d3e"),
                            Active = true,
                            Name = "The L'tokk Khrask",
                            Url = "https://twilight-imperium.fandom.com/wiki/L%27tokk_Khrask_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("7f81ab5d-6e70-4c5d-b1be-9a0b1c2d3e4f"),
                            Active = true,
                            Name = "The Mirveda Protectorate",
                            Url = "https://twilight-imperium.fandom.com/wiki/Mirveda_Protectorate_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("8092bc6e-7f81-4d6e-c2cf-0b1c2d3e4f50"),
                            Active = true,
                            Name = "The Glimmer of Mortheus",
                            Url = "https://twilight-imperium.fandom.com/wiki/Glimmer_of_Mortheus_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("91a3cd7f-8092-4e7f-d3d0-1c2d3e4f5061"),
                            Active = true,
                            Name = "The Myko-Mentori",
                            Url = "https://twilight-imperium.fandom.com/wiki/Myko-Mentori_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("a2b4de80-91a3-4f80-e4e1-2d3e4f506172"),
                            Active = true,
                            Name = "The Nivyn Star Kings",
                            Url = "https://twilight-imperium.fandom.com/wiki/Nivyn_Star_Kings_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("b3c5ef91-a2b4-4091-f5f2-3e4f50617283"),
                            Active = true,
                            Name = "The Olradin League",
                            Url = "https://twilight-imperium.fandom.com/wiki/Olradin_League_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("c4d60102-b3c5-4102-0603-4f5061728394"),
                            Active = true,
                            Name = "The Zealots of Rhodun",
                            Url = "https://twilight-imperium.fandom.com/wiki/Zealots_of_Rhodun_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("d5e71213-c4d6-4203-1714-506172839405"),
                            Active = true,
                            Name = "Roh'Dhna Mechatronics",
                            Url = "https://twilight-imperium.fandom.com/wiki/Roh%27Dhna_Mechatronics_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("e6f82324-d5e7-4304-2825-617283940516"),
                            Active = true,
                            Name = "The Tnelis Syndicate",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Tnelis_Syndicate_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("f7093425-e6f8-4405-3936-728394051627"),
                            Active = true,
                            Name = "The Vaden Banking Clans",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Vaden_Banking_Clans_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("0a1a4536-f709-4506-4a47-839405162738"),
                            Active = true,
                            Name = "The Vaylerian Scourge",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Vaylerian_Scourge_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("1b2b5647-0a1a-4607-5b58-940516273849"),
                            Active = true,
                            Name = "The Veldyr Sovereignty",
                            Url = "https://twilight-imperium.fandom.com/wiki/The_Veldyr_Sovereignty_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("2c3c6758-1b2b-4708-6c69-a4051627384a"),
                            Active = true,
                            Name = "The Zelian Purifier",
                            Url = "https://twilight-imperium.fandom.com/wiki/Zelian_Purifier_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("3d4d7869-2c3c-4809-7d7a-b5162738495b"),
                            Active = true,
                            Name = "The Bentor Conglomerate",
                            Url = "https://twilight-imperium.fandom.com/wiki/Bentor_Conglomerate_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("4e5e897a-3d4d-490a-8e8b-c62738495c6c"),
                            Active = true,
                            Name = "The Cheiran Hordes",
                            Url = "https://twilight-imperium.fandom.com/wiki/Cheiran_Hordes_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("5f6f9a8b-4e5e-4a0b-9f9c-d738495c6d7d"),
                            Active = true,
                            Name = "The Edyn Mandate",
                            Url = "https://twilight-imperium.fandom.com/wiki/Edyn_Mandate_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("6070ab9c-5f6f-4b1c-a0ad-e8495c6d7e8e"),
                            Active = true,
                            Name = "The Ghoti Wayfarers",
                            Url = "https://twilight-imperium.fandom.com/wiki/Ghoti_Wayfarers_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("7181bcad-6070-4c2d-b1be-f95c6d7e8f9f"),
                            Active = true,
                            Name = "The GLEdge Union",
                            Url = "https://twilight-imperium.fandom.com/wiki/Gledge_Union_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("8292cdbe-7181-4d3e-c2cf-0a6d7e8f9010"),
                            Active = true,
                            Name = "The Berserkers of Kjalengard",
                            Url = "https://twilight-imperium.fandom.com/wiki/Berserkers_of_Kjalengard_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("93a3decf-8292-4e4f-d3e0-1b7e8f901121"),
                            Active = true,
                            Name = "The Monks of Kolume",
                            Url = "https://twilight-imperium.fandom.com/wiki/Monks_of_Kolume_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("a4b4ef00-93a3-4f50-e4f1-2c8f90112132"),
                            Active = true,
                            Name = "The Kyro Sodality",
                            Url = "https://twilight-imperium.fandom.com/wiki/Kyro_Sodality_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("b5c50111-a4b4-5051-f502-3d9011213243"),
                            Active = true,
                            Name = "The Lanefir Remnants",
                            Url = "https://twilight-imperium.fandom.com/wiki/Lanefir_Remnants_(UNOFFICIAL)"
                        },
                        new
                        {
                            Identifier = new Guid("c6d61222-b5c5-5162-0603-4e1121324354"),
                            Active = true,
                            Name = "The Nokar Sellships",
                            Url = "https://twilight-imperium.fandom.com/wiki/Nokar_Sellships_(UNOFFICIAL)"
                        });
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.FactionVariant", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FactionIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Identifier");

                    b.HasIndex("FactionIdentifier");

                    b.ToTable("FactionVariants");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("3852bc1c-57d8-44fc-932f-9216c8eebdba"),
                            FactionIdentifier = new Guid("51ee1c82-279b-444c-a6aa-a8cd475612fd"),
                            Name = "The Mentak Coalition"
                        },
                        new
                        {
                            Identifier = new Guid("9c01e321-475d-447e-9d5a-e8d6b11ea828"),
                            FactionIdentifier = new Guid("51ee1c82-279b-444c-a6aa-a8cd475612fd"),
                            Name = "The Xxcha Kingdom"
                        },
                        new
                        {
                            Identifier = new Guid("f487ab41-107f-4a08-8a3c-5f8eade06e2c"),
                            FactionIdentifier = new Guid("51ee1c82-279b-444c-a6aa-a8cd475612fd"),
                            Name = "The Argent Flight"
                        });
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Person", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DefaultColourIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Identifier");

                    b.HasIndex("DefaultColourIdentifier");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Play", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Map")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PointGoal")
                        .HasColumnType("bigint");

                    b.Property<double>("RulesVersion")
                        .HasColumnType("float");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Identifier");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Player", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColourIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DraftOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("Eliminated")
                        .HasColumnType("bit");

                    b.Property<Guid>("FactionIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<bool>("Winner")
                        .HasColumnType("bit");

                    b.HasKey("Identifier");

                    b.HasIndex("ColourIdentifier");

                    b.HasIndex("FactionIdentifier");

                    b.HasIndex("PersonIdentifier");

                    b.HasIndex("PlayIdentifier");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Variant", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Identifier");

                    b.ToTable("Variants");

                    b.HasData(
                        new
                        {
                            Identifier = new Guid("7f1c0478-b6c1-4ca6-bc79-78912315e947"),
                            Name = "Setup - Competitive"
                        },
                        new
                        {
                            Identifier = new Guid("27267f67-8243-4448-b71f-8e6c366e2fc8"),
                            Name = "Setup - Cooperative"
                        },
                        new
                        {
                            Identifier = new Guid("b28554aa-f0a4-4fd0-adc1-37480b2be570"),
                            Name = "Setup - Prebuilt"
                        },
                        new
                        {
                            Identifier = new Guid("eaed8375-d283-49ee-9224-93460c91be31"),
                            Name = "Setup - Milty"
                        },
                        new
                        {
                            Identifier = new Guid("84ee1c98-9b0c-467c-9c6d-b7cdd2e4a9c9"),
                            Name = "Mode - Alliance"
                        },
                        new
                        {
                            Identifier = new Guid("4c0e5036-8a98-4729-ade2-48fded663369"),
                            Name = "Mode - Pax Magnifica"
                        },
                        new
                        {
                            Identifier = new Guid("3e2f6313-8387-4010-a5f0-abb6adc5db61"),
                            Name = "Rule - No Support Swaps"
                        },
                        new
                        {
                            Identifier = new Guid("2367d7be-98ca-4f64-85f1-efb433f9c582"),
                            Name = "Rule - Public Objectives Visible"
                        },
                        new
                        {
                            Identifier = new Guid("8e0c451b-5137-4dee-b212-7077e8487c23"),
                            Name = "Rule - 4/4/4"
                        });
                });

            modelBuilder.Entity("PlayVariant", b =>
                {
                    b.Property<Guid>("PlaysIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VariantsIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlaysIdentifier", "VariantsIdentifier");

                    b.HasIndex("VariantsIdentifier");

                    b.ToTable("PlayVariant");
                });

            modelBuilder.Entity("ContentPlay", b =>
                {
                    b.HasOne("MecatolArchives.DataAccess.Models.Content", null)
                        .WithMany()
                        .HasForeignKey("ExpansionsIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecatolArchives.DataAccess.Models.Play", null)
                        .WithMany()
                        .HasForeignKey("PlaysIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.FactionVariant", b =>
                {
                    b.HasOne("MecatolArchives.DataAccess.Models.Faction", "Faction")
                        .WithMany("Variants")
                        .HasForeignKey("FactionIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Person", b =>
                {
                    b.HasOne("MecatolArchives.DataAccess.Models.Colour", "DefaultColour")
                        .WithMany()
                        .HasForeignKey("DefaultColourIdentifier");

                    b.Navigation("DefaultColour");
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Player", b =>
                {
                    b.HasOne("MecatolArchives.DataAccess.Models.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecatolArchives.DataAccess.Models.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecatolArchives.DataAccess.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecatolArchives.DataAccess.Models.Play", "Play")
                        .WithMany("Players")
                        .HasForeignKey("PlayIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("Faction");

                    b.Navigation("Person");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("PlayVariant", b =>
                {
                    b.HasOne("MecatolArchives.DataAccess.Models.Play", null)
                        .WithMany()
                        .HasForeignKey("PlaysIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecatolArchives.DataAccess.Models.Variant", null)
                        .WithMany()
                        .HasForeignKey("VariantsIdentifier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Faction", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("MecatolArchives.DataAccess.Models.Play", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
