<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.0.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>2a95a3d4-0b1c-488d-b888-3577f955f04b</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MecatolArchives.ApiService\MecatolArchives.ApiService.csproj" />
    <ProjectReference Include="..\MecatolArchives.Web\MecatolArchives.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>
</Project>