name: docker-latest

on:
  push:
    branches:
      - 'main'

jobs:
  docker-latest:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERPASSWORD }}
          registry: ${{ secrets.DOCKERREGISTRY }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Publish Website
        run: dotnet publish Website/Website.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerRegistry=${{ secrets.DOCKERREGISTRY }} -p:ContainerRepository=mecatol_archives_website -p:ContainerImageTag=latest
      - name: Publish API
        run: dotnet publish API/API.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerRegistry=${{ secrets.DOCKERREGISTRY }} -p:ContainerRepository=mecatol_archives_api -p:ContainerImageTag=latest